### ISSUE TITLE
Not working ida 32bit

### ISSUE THREAD

**Issue by d3nish** [nforest/droidimg#24]
I can't do it when I select Ida 32bit or I launch it from 32bit icon and than script option isn't there but for 64bit it's there.
Why?
Is it a bug?

**Comment by idl3r** [comment]
It is designed to work with both 32 and 64bit IDA Pro. What's the specific problem? Was the loader not showing up or failed to parse the kernel?

**Comment by 0xXA** [comment]
> It is designed to work with both 32 and 64bit IDA Pro. What's the specific problem? Was the loader not showing up or failed to parse the kernel?

Not showing up

**Comment by d3nish** [comment]
Yep man not showing up

**Comment by 0xXA** [comment]
Any update ?
I can't see thus bug fixed

**Comment by d3nish** [comment]
Any update?

**Comment by idl3r** [comment]
Earlier version of IDA may encounter problem of missing builtin packages (for forward compatibility). Try IDA 7 or later, or fallback to commit b171bca2668fdbb3cfd0bd7ca16c7d96875aec2d. If still not showing up, I believe it's IDA support you need to talk to, or it's time to give Ghidra a try.

**Comment by d3nish** [comment]
I'm using Ida 7.0
