### ISSUE TITLE
Hi can u try disassemble this?

### ISSUE THREAD

**Issue by d3nish** [nforest/droidimg#26]
It's not working for me when use ur script
https://drive.google.com/file/d/1p94WBWFJCo9vtOvWleLfmaSvh-I-fFOF/view?usp=sharing

Not working for me
If it works for you than can you try giving me the database of this exported from Ida ?

**Comment by idl3r** [comment]
Actually, it works. You need to extract the real linux kernel image from the boot.img first. You can do that with abootimg, binwalk, dd and gzip, all are common utilities. Search XDA for tutorials.

I'm using Ghidra now, this is the output for Ghidra load with GhidraVmlinuxLoader. For practice, you shall extract the kernel image (vmlinux) yourself. 
[vmlinux.sym.json.zip](https://github.com/nforest/droidimg/files/3006259/vmlinux.sym.json.zip)

Droidimg was designed for experienced researchers. But seems there are wider user base of it now. I'll update the README with a section describing how to quickly check if a file is a valid vmlinux image.

**Comment by d3nish** [comment]
Dude I have extracted image from kernel with one of the utilities you have mentioned above and it still not showing on Ida page
