### ISSUE TITLE
does not work with pixel 6a kernel.

### ISSUE THREAD

**Issue by Zibri** [nforest/droidimg#59]
Firmware version 13.0.0 (TQ1A.221205.011, Dec 2022)
Pixel6a

index string out of range.

**Comment by Zibri** [comment]
$ python3 ../droidimg/vmlinux.py kernel
b'Linux version 5.10.107-android13-4-00038-ga6f610f1f1e6-ab9083768 (build-user@build-host) (Android (8508608, based on r450784e) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6), LLD 14.0.7) #1 SMP PREEMPT Tue Sep 20 02:33:52 UTC 2022'
[+]kallsyms_arch = arm64
[!]could be offset table...
[+]numsyms: 140053
[+]kallsyms_address_table = 0x1fbc4a8
[+]kallsyms_relative_base = 0xffffffc010000000
[+]kallsyms_num = 140053 (140053)
[+]kallsyms_name_table = 0x2045110
[+]kallsyms_type_table = 0x0
[+]kallsyms_marker_table = 0x2232a94
[+]kallsyms_token_table = 0x2233bb4
[+]kallsyms_token_index_table = 0x22ff5b4
Traceback (most recent call last):
  File "../droidimg/vmlinux.py", line 1181, in <module>
    main(sys.argv)
  File "../droidimg/vmlinux.py", line 1163, in main
    parse_vmlinux(args.image, sys.stderr, sys.stdout)
  File "../droidimg/vmlinux.py", line 1149, in parse_vmlinux
    do_kallsyms(kallsyms, vmlinux)
  File "../droidimg/vmlinux.py", line 787, in do_kallsyms
    do_name_table(kallsyms, offset, vmlinux)
  File "../droidimg/vmlinux.py", line 389, in do_name_table
    kallsyms['type'].append(name[0])
IndexError: string index out of range

**Comment by Zibri** [comment]
$ python3 ../droidimg/vmlinux.py kernel
b'Linux version 5.10.107-android13-4-00038-ga6f610f1f1e6-ab9083768 (build-user@build-host) (Android (8508608, based on r450784e) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6), LLD 14.0.7) #1 SMP PREEMPT Tue Sep 20 02:33:52 UTC 2022'
[+]kallsyms_arch = arm64
[!]could be offset table...
[+]numsyms: 140053
[+]kallsyms_address_table = 0x1fbc4a8
[+]kallsyms_relative_base = 0xffffffc010000000
[+]kallsyms_num = 140053 (140053)
[+]kallsyms_name_table = 0x2045110
[+]kallsyms_type_table = 0x0
[+]kallsyms_marker_table = 0x2232a94
[+]kallsyms_token_table = 0x2233bb4
[+]kallsyms_token_index_table = 0x22ff5b4
Traceback (most recent call last):
  File "../droidimg/vmlinux.py", line 1181, in <module>
    main(sys.argv)
  File "../droidimg/vmlinux.py", line 1163, in main
    parse_vmlinux(args.image, sys.stderr, sys.stdout)
  File "../droidimg/vmlinux.py", line 1149, in parse_vmlinux
    do_kallsyms(kallsyms, vmlinux)
  File "../droidimg/vmlinux.py", line 787, in do_kallsyms
    do_name_table(kallsyms, offset, vmlinux)
  File "../droidimg/vmlinux.py", line 389, in do_name_table
    kallsyms['type'].append(name[0])
IndexError: string index out of range

**Comment by idl3r** [comment]
It now works with this particular kernel.
[kallsyms.txt](https://github.com/nforest/droidimg/files/13406665/kallsyms.txt)
