### ISSUE TITLE
r2 support

### ISSUE THREAD

**Issue by lowlyw** [nforest/droidimg#6]
support for radare2 can be useful

https://gist.github.com/anonymous/008aaaa48262a3dc34eac206d2a8c0e5

for example is hacky, would you be interested in a more polished version that supports both ida and r2?

**Comment by nforest** [comment]
Thanks for your code, now I have merged it into vmlinux.py and changed a little bit, plz try it:)

**Comment by lowlyw** [comment]
looks good thanks for merging 👍
