### ISSUE TITLE
Does not work SAMSUNG Galaxy A33 5G

### ISSUE THREAD

**Issue by MalHyuk** [nforest/droidimg#60]
[My ENV]
OS : Windows 10 x64 Enterprise
i use IDA 7.5
My android device is SAMSUNG Galaxy A33 5G(`A336NKSU3CWB3`)
Security Patch : 2023-02-01

Can't find `_start`  in android kernel image

### IDA Warning log
```python
C:\IDA Pro 7.5\loaders\vmlinux.py: Traceback (most recent call last):
  File "C:/IDA Pro 7.5/loaders/vmlinux.py", line 1028, in load_file
    do_kallsyms(kallsyms, vmlinux)
  File "C:/IDA Pro 7.5/loaders/vmlinux.py", line 788, in do_kallsyms
    do_guess_start_address(kallsyms, vmlinux)
  File "C:/IDA Pro 7.5/loaders/vmlinux.py", line 459, in do_guess_start_address
    assert False,"  [!]kernel start address error..."
AssertionError:   [!]kernel start address error...
```

how to fix?

**Comment by idl3r** [comment]
It now works with this particular kernel.
[kallsyms.txt](https://github.com/nforest/droidimg/files/13407907/kallsyms.txt)
